spring:
  datasource:
    url: jdbc:postgresql://hr-userdb-pg13:5432/db_hr_user
    username: admin
    password: 1234567
  
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
