spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_hr_user
    username: admin
    password: 1234567
  
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
            
      hibernate:
        hbm2ddl:
          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: true
